
import numpy as np

def write_cube(lut, path, title="LoR-IA-3DLUT", domain_min=0.0, domain_max=1.0):
    """
    lut: numpy array [G,G,G,3] in [0,1], identity-aligned with R,G,B axes.
    Writes an .cube file (1D LUT header with 3D LUT body per CUBE spec).
    """
    G = lut.shape[0]
    with open(path, "w", encoding="utf-8") as f:
        f.write(f"# Generated by LoR-IA-3DLUT Starter\n")
        f.write(f"TITLE \"{title}\"\n")
        f.write(f"LUT_3D_SIZE {G}\n")
        f.write(f"DOMAIN_MIN {domain_min} {domain_min} {domain_min}\n")
        f.write(f"DOMAIN_MAX {domain_max} {domain_max} {domain_max}\n")
        # CUBE expects r-fastest ordering across the grid.
        for b in range(G):
            for g in range(G):
                for r in range(G):
                    v = lut[r,g,b]  # [3]
                    f.write(f"{float(v[0]):.6f} {float(v[1]):.6f} {float(v[2]):.6f}\n")
